### ISSUE TITLE
Could you provide the documentation of GTLC+?

### ISSUE THREAD

**Issue by nyngwang** [Gradual-Typing/Grift#105]
For example I don't know what's the meaning of `box (- n 1)` or `repeat (j l h)` in your paper. Could you provide some simple description or code example?

by the way I guess I found an typo on your paper:

I think the line `[i: (Ref Int) (box (- h 1))]` would be `... box(- l 1))]`, or `i > h` will happen.

![image](https://user-images.githubusercontent.com/24765272/80192914-80831e80-864a-11ea-9060-1ae94bf09c74.jpeg)

**Comment by deyaaeldeen** [comment]
You are correct, this is a typo in the paper. 

`(box (- n 1))` allocates a reference and initializes it to `(- n 1)`.
`(repeat (j l h) e)` creates a loop with index `j` initialized to `l` and is incremented by 1 at the end of each iteration and the loop continues until `j = h`. `e` is executed in each iteration with a new value of `j`.
