### ISSUE TITLE
Bug while compiling with --no-dyn-operations

### ISSUE THREAD

**Issue by Temurson** [Gradual-Typing/Grift#113]
When trying to do `grift --no-dyn-operations --type-based-casts tests/suite/tuples/tuple4.grift`, I'm getting an error on this [line](https://github.com/Gradual-Typing/Grift/blob/32875ae4a6aab25388cacfb2b1788db3cce726f6/src/grift/insert-casts.rkt#L437) in `src/grift/insert-casts.rkt`. Here's the error:
```
n: undefined;
 cannot use before initialization
```
`n` in this code seems to be the size of the tuple, although I'm not sure.

**Comment by akuhlens** [comment]
The `n` on the right hand side of that define should probably be `i`, but that goes to show how recently this code has been tested. There are likely other bugs. If you want to patch this up and submit a pull request that would be awesome. Otherwise I will try to fix it after work today.

**Comment by Temurson** [comment]
Sure, I also thought this was `i`, but wanted to make sure. I'll submit a pull request later today (hopefully today).
