### ISSUE TITLE
Prerequisite software for installing grift?

### ISSUE THREAD

**Issue by peter-campora** [Gradual-Typing/Grift#85]
Hello, I've been trying to install grift via raco (on Racket 7.4) on Ubuntu 18.04. What other pieces of software are prerequisites to installing grift? I've attached a log of the output when trying to install. It's a fresh installation, so many packages could be missing.
[grift-output.txt](https://github.com/Gradual-Typing/Grift/files/3714884/grift-output.txt)

**Comment by deyaaeldeen** [comment]
Hi Peter,

It looks like your installation succeeded to me. I believe if you run `make test`, it will run Grift's testsuite without problems.

Generally, you only need Racket and a C compiler to build and use Grift. Also, if you are interested, we have a Docker image for benchmarking: https://github.com/Gradual-Typing/benchmarks

**Comment by peter-campora** [comment]
Ah sorry, I thought that grift would be added to my path after installation. But now I see that there is something installed in ~/.racket/7.4/bin. I haven't tested it on any input files, but I'll close the issue!

Thanks for the pointer. I am interested in using Grift for benchmarking and will definitely take a look at that. I plan to implement a specific form of cast insertion on top of Grift, so I may message with questions about the codebase :)
